version: "3"
# Thanks to https://visibilityspots.org/dockerized-cloudflared-pi-hole.html
# echo "alias dns-up='cd /path/to/folder; docker-compose up -d'" >> ~/.bash_profile
services:
  cloudflared:
    container_name: cloudflared
    # image: fardog/secureoperator:latest # google dns
    image: visibilityspots/cloudflared:latest
    restart: unless-stopped
    ports:
      - "5053:5054/tcp"
      - "5053:5054/udp"
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2
    dns:
      - 1.1.1.1
      - 1.0.0.1
  
  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    restart: unless-stopped
    volumes:
      - './forward-records.conf:/opt/unbound/etc/unbound/forward-records.conf:ro'
    ports:
      - "5153:53/tcp"
      - "5153:53/udp"
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "8111:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      ServerIP: 10.0.0.4
      DNS1: 10.0.0.3
      DNS2: 10.0.0.3
      IPv6: 'false'
      TZ: Asia/Kolkata
      DNSMASQ_LISTENING: all
      WEBPASSWORD: AdBl0ck3r
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    networks:
      pihole_net:
        ipv4_address: 10.0.0.4
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN

networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
